<?php
/**
 * Repair accessibility issues in final markup generated by Bricks templates.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Apply server-side fixes that must be present before frontend JavaScript runs.
 *
 * @param string $html Complete frontend response markup.
 * @return string
 */
function bemke_child_prepare_accessibility_markup( $html ) {
	if ( ! is_string( $html ) || '' === $html ) {
		return $html;
	}

	$html = bemke_child_prepare_accessibility_toolbar_buttons( $html );
	$html = bemke_child_prepare_polish_menu_labels( $html );
	$html = bemke_child_repair_form_group_labels( $html );
	$html = bemke_child_prepare_form_accessibility_attributes( $html );
	$html = bemke_child_repair_footer_social_links( $html );
	$html = bemke_child_prepare_descriptive_resource_links( $html );
	$html = bemke_child_prepare_youtube_story_links( $html );
	$html = bemke_child_prepare_decorative_videos( $html );

	return $html;
}

/**
 * Convert Bricks links used as toolbar controls into native buttons.
 *
 * @param string $html Complete frontend response markup.
 * @return string
 */
function bemke_child_prepare_accessibility_toolbar_buttons( $html ) {
	$controls = array(
		'brxe-qmbqwm' => array( 'Normalny rozmiar tekstu', 'true' ),
		'brxe-cqxcbv' => array( 'Duży rozmiar tekstu', 'false' ),
		'brxe-toalqu' => array( 'Bardzo duży rozmiar tekstu', 'false' ),
		'brxe-pxhfen' => array( 'Domyślny kontrast', 'true' ),
		'brxe-wdrqee' => array( 'Biały tekst na czarnym tle', 'false' ),
		'brxe-jydvjv' => array( 'Czarny tekst na żółtym tle', 'false' ),
		'brxe-pnbult' => array( 'Żółty tekst na czarnym tle', 'false' ),
	);

	foreach ( $controls as $control_id => $control ) {
		$pattern      = '/<a\b(?=[^>]*\bid\s*=\s*(["\'])' . preg_quote( $control_id, '/' ) . '\1)([^>]*)>(.*?)<\/a>/is';
		$updated_html = preg_replace_callback(
			$pattern,
			static function ( $matches ) use ( $control ) {
				$attributes = bemke_child_remove_html_attributes(
					$matches[2],
					array( 'href', 'target', 'rel', 'role', 'tabindex', 'aria-label', 'aria-pressed', 'title', 'type' )
				);

				return sprintf(
					'<button type="button"%1$s aria-label="%2$s" aria-pressed="%3$s" title="%2$s">%4$s</button>',
					$attributes,
					esc_attr( $control[0] ),
					esc_attr( $control[1] ),
					$matches[3]
				);
			},
			$html,
			1
		);

		if ( null !== $updated_html ) {
			$html = $updated_html;
		}
	}

	return $html;
}

/**
 * Replace Bricks' initial English menu-control names before first paint. The
 * frontend menu modules keep these labels synchronized with aria-expanded.
 *
 * @param string $html Complete frontend response markup.
 * @return string
 */
function bemke_child_prepare_polish_menu_labels( $html ) {
	$mobile_toggle_pattern = '/<button\b(?=[^>]*\bclass\s*=\s*(["\'])[^"\']*\bbricks-mobile-menu-toggle\b[^"\']*\1)[^>]*>/i';
	$updated_html          = preg_replace_callback(
		$mobile_toggle_pattern,
		static function ( $matches ) {
			$button = bemke_child_remove_html_attributes( $matches[0], array( 'aria-label' ) );
			$label  = preg_match( '/\baria-expanded\s*=\s*(["\'])true\1/i', $button )
				? 'Zamknij menu główne'
				: 'Otwórz menu główne';

			return preg_replace(
				'/>$/',
				' aria-label="' . esc_attr( $label ) . '">',
				$button,
				1
			) ?? $matches[0];
		},
		$html
	);

	if ( null !== $updated_html ) {
		$html = $updated_html;
	}

	$submenu_pattern = '/<button\b(?=[^>]*\baria-label\s*=\s*(["\'])([^"\']+?)\s+Sub menu\1)[^>]*>/iu';
	$updated_html    = preg_replace_callback(
		$submenu_pattern,
		static function ( $matches ) {
			$button     = bemke_child_remove_html_attributes( $matches[0], array( 'aria-label' ) );
			$is_open    = (bool) preg_match( '/\baria-expanded\s*=\s*(["\'])true\1/i', $button );
			$item_label = trim( wp_strip_all_tags( html_entity_decode( $matches[2], ENT_QUOTES, 'UTF-8' ) ) );
			$label      = ( $is_open ? 'Zamknij podmenu: ' : 'Otwórz podmenu: ' ) . $item_label;

			return preg_replace(
				'/>$/',
				' aria-label="' . esc_attr( $label ) . '">',
				$button,
				1
			) ?? $matches[0];
		},
		$html
	);

	return null === $updated_html ? $html : $updated_html;
}

/**
 * Replace broken form-group label references with an accessible group name.
 *
 * Bricks emits aria-labelledby="label-…" for checkbox groups but does not
 * render an element with that ID when the field label is visually omitted.
 *
 * @param string $html Complete frontend response markup.
 * @return string
 */
function bemke_child_repair_form_group_labels( $html ) {
	$pattern = '/<div\b(?=[^>]*\bclass\s*=\s*(["\'])[^"\']*\bform-group\b[^"\']*\1)(?=[^>]*\baria-labelledby\s*=\s*(["\'])([^"\']+)\2)[^>]*>.*?<\/div>/is';

	$updated_html = preg_replace_callback(
		$pattern,
		static function ( $matches ) use ( $html ) {
			$references = preg_split( '/\s+/', trim( $matches[3] ) );
			$has_target = false;

			foreach ( $references as $reference ) {
				if (
					'' !== $reference &&
					preg_match(
						'/\bid\s*=\s*(["\'])' . preg_quote( $reference, '/' ) . '\1/i',
						$html
					)
				) {
					$has_target = true;
					break;
				}
			}

			if ( $has_target ) {
				return $matches[0];
			}

			$label = 'Opcje formularza';

			if ( preg_match( '/\btype\s*=\s*(["\'])checkbox\1/i', $matches[0] ) ) {
				$label = false !== stripos( $matches[0], 'required' )
					? 'Wymagane zgody'
					: 'Dodatkowe zgody';
			} elseif ( preg_match( '/\btype\s*=\s*(["\'])radio\1/i', $matches[0] ) ) {
				$label = 'Wybierz jedną opcję';
			}

			$opening_tag = strstr( $matches[0], '>', true );

			if ( false === $opening_tag ) {
				return $matches[0];
			}

			$opening_tag = preg_replace(
				'/\saria-labelledby\s*=\s*(["\'])[^"\']*\1/i',
				'',
				$opening_tag,
				1
			);

			if ( null === $opening_tag ) {
				return $matches[0];
			}

			$opening_tag .= ' aria-label="' . esc_attr( $label ) . '">';

			return $opening_tag . substr( $matches[0], strpos( $matches[0], '>' ) + 1 );
		},
		$html
	);

	return null === $updated_html ? $html : $updated_html;
}

/**
 * Add non-visual accessibility attributes to the homepage and services forms.
 * Visible field labels remain under Bricks control, so this pass cannot alter
 * their design.
 *
 * @param string $html Complete frontend response markup.
 * @return string
 */
function bemke_child_prepare_form_accessibility_attributes( $html ) {
	$forms = array(
		'brxe-afpmhc' => array(
			'form-field-a4f8b2' => 'name',
			'form-field-dba4f2' => 'email',
		),
		'brxe-pvoywb' => array(
			'form-field-cd9802' => 'name',
			'form-field-57b3cb' => 'email',
		),
	);

	foreach ( $forms as $form_id => $autocomplete_fields ) {
		$form_pattern = '/<form\b(?=[^>]*\bid\s*=\s*(["\'])' . preg_quote( $form_id, '/' ) . '\1)[^>]*>.*?<\/form>/is';
		$updated_html = preg_replace_callback(
			$form_pattern,
			static function ( $form_matches ) use ( $autocomplete_fields ) {
				$form_markup = $form_matches[0];

				// Every group in these forms contains one labelled control, so group
				// semantics add noise without conveying a real relationship.
				$form_markup = preg_replace_callback(
					'/<div\b(?=[^>]*\bclass\s*=\s*(["\'])[^"\']*\bform-group\b[^"\']*\1)[^>]*>/i',
					static function ( $group_matches ) {
						return bemke_child_remove_html_attributes(
							$group_matches[0],
							array( 'role', 'aria-label', 'aria-labelledby' )
						);
					},
					$form_markup
				) ?? $form_markup;

				foreach ( $autocomplete_fields as $field_id => $autocomplete ) {
					$field_pattern = '/<input\b(?=[^>]*\bid\s*=\s*(["\'])' . preg_quote( $field_id, '/' ) . '\1)[^>]*>/i';
					$form_markup   = preg_replace_callback(
						$field_pattern,
						static function ( $field_matches ) use ( $autocomplete ) {
							$field_tag = bemke_child_remove_html_attributes(
								$field_matches[0],
								array( 'autocomplete' )
							);

							return preg_replace(
								'/\s*\/?>$/',
								' autocomplete="' . esc_attr( $autocomplete ) . '">',
								$field_tag,
								1
							) ?? $field_tag;
						},
						$form_markup,
						1
					) ?? $form_markup;
				}

				return $form_markup;
			},
			$html,
			1
		);

		if ( null !== $updated_html ) {
			$html = $updated_html;
		}
	}

	return $html;
}

/**
 * Repair invalid nested anchors used by the social icons in the footer.
 *
 * @param string $html Complete frontend response markup.
 * @return string
 */
function bemke_child_repair_footer_social_links( $html ) {
	$pattern = '/<a\b([^>]*\bclass\s*=\s*(["\'])[^"\']*\bsocial-link\b[^"\']*\2[^>]*)>\s*(<a\b.*?<\/a>)\s*<\/a>/is';

	$updated_html = preg_replace_callback(
		$pattern,
		static function ( $matches ) {
			$wrapper_attributes = bemke_child_remove_html_attributes(
				$matches[1],
				array( 'href', 'target', 'rel', 'role', 'tabindex', 'aria-label' )
			);
			$inner_link         = $matches[3];
			$label              = bemke_child_get_social_link_label( $inner_link );

			if ( '' !== $label ) {
				$inner_link = preg_replace_callback(
					'/<a\b([^>]*)>/i',
					static function ( $link_matches ) use ( $label ) {
						$link_attributes = bemke_child_remove_html_attributes(
							$link_matches[1],
							array( 'aria-label', 'rel' )
						);

						return '<a' . $link_attributes . ' aria-label="' . esc_attr( $label ) . '" rel="noopener noreferrer">';
					},
					$inner_link,
					1
				) ?? $inner_link;
			}

			return '<div' . $wrapper_attributes . '>' . $inner_link . '</div>';
		},
		$html
	);

	if ( null !== $updated_html ) {
		$html = $updated_html;
	}

	/*
	 * Current Bricks markup uses one social-link anchor containing an SVG. Give
	 * that link an accessible name directly in the initial server response.
	 */
	$single_link_pattern = '/<a\b(?=[^>]*\bclass\s*=\s*(?:"[^"]*\bsocial-link\b[^"]*"|\'[^\']*\bsocial-link\b[^\']*\'))([^>]*)>/is';
	$updated_html        = preg_replace_callback(
		$single_link_pattern,
		static function ( $matches ) {
			$label = bemke_child_get_social_link_label( $matches[0] );

			if ( '' === $label ) {
				return $matches[0];
			}

			$link_attributes = bemke_child_remove_html_attributes(
				$matches[1],
				array( 'aria-label', 'rel' )
			);

			return '<a' . $link_attributes . ' aria-label="' . esc_attr( $label ) . '" rel="noopener noreferrer">';
		},
		$html
	);

	return null === $updated_html ? $html : $updated_html;
}

/**
 * Resolve the Polish accessible name for a supported social network link.
 *
 * @param string $markup Link tag or markup containing its URL.
 * @return string
 */
function bemke_child_get_social_link_label( $markup ) {
	if ( false !== stripos( $markup, 'instagram.com' ) ) {
		return 'Profil Bemke na Instagramie';
	}

	if ( false !== stripos( $markup, 'linkedin.com' ) ) {
		return 'Profil Bemke na LinkedInie';
	}

	if ( false !== stripos( $markup, 'facebook.com' ) ) {
		return 'Profil Bemke na Facebooku';
	}

	return '';
}

/**
 * Replace generic resource-link wording with a purpose that makes sense out
 * of context and identifies the file format.
 *
 * @param string $html Complete frontend response markup.
 * @return string
 */
function bemke_child_prepare_descriptive_resource_links( $html ) {
	$pattern = '/(<a\b(?=[^>]*\bhref\s*=\s*(["\'])[^"\']*Regulamin-Rekrutacji_STEAM-Academy_2_pdf\.pdf(?:[?#][^"\']*)?\2)[^>]*>)\s*Link\s*(<\/a>)/iu';

	$updated_html = preg_replace(
		$pattern,
		'$1Regulamin rekrutacji (PDF)$3',
		$html,
		1
	);

	return null === $updated_html ? $html : $updated_html;
}

/**
 * Give the three Bemke Explore story links unique Polish names while keeping
 * their visible wording concise. WAVE will still report an informational
 * YouTube alert because the destination is a video service.
 *
 * @param string $html Complete frontend response markup.
 * @return string
 */
function bemke_child_prepare_youtube_story_links( $html ) {
	$stories = array(
		'brxe-xoqgdq' => 'Zobacz film — historia Olka w serwisie YouTube (otwiera się w nowej karcie)',
		'brxe-zrhhrq' => 'Zobacz film — historia Ani w serwisie YouTube (otwiera się w nowej karcie)',
		'brxe-casnvb' => 'Zobacz film — historia Anity w serwisie YouTube (otwiera się w nowej karcie)',
	);

	foreach ( $stories as $link_id => $label ) {
		$pattern      = '/<a\b(?=[^>]*\bid\s*=\s*(["\'])' . preg_quote( $link_id, '/' ) . '\1)([^>]*)>.*?<\/a>/is';
		$updated_html = preg_replace_callback(
			$pattern,
			static function ( $matches ) use ( $label ) {
				$link_attributes = bemke_child_remove_html_attributes(
					$matches[2],
					array( 'aria-label', 'rel' )
				);

				return '<a' . $link_attributes . ' aria-label="' . esc_attr( $label ) . '" rel="noopener noreferrer">Zobacz film</a>';
			},
			$html,
			1
		);

		if ( null !== $updated_html ) {
			$html = $updated_html;
		}
	}

	return $html;
}

/**
 * Mark muted decorative autoplay videos as non-interactive from first paint.
 * This includes looping backgrounds and the short campaign-book animation.
 *
 * @param string $html Complete frontend response markup.
 * @return string
 */
function bemke_child_prepare_decorative_videos( $html ) {
	$pattern = '/<video\b(?=[^>]*\bmuted\b)(?:(?=[^>]*\bautoplay\b)(?=[^>]*\bloop\b)|(?=[^>]*(?:Comp-6\.webm|\bdata-bemke-alpha-sources\b)))[^>]*>/i';

	$updated_html = preg_replace_callback(
		$pattern,
		static function ( $matches ) {
			$tag = bemke_child_remove_html_attributes(
				$matches[0],
				array( 'onclick', 'controls', 'aria-hidden', 'tabindex' )
			);

			return preg_replace(
				'/>$/',
				' aria-hidden="true" tabindex="-1">',
				$tag,
				1
			) ?? $matches[0];
		},
		$html
	);

	return null === $updated_html ? $html : $updated_html;
}

/**
 * Remove named attributes from an HTML tag attribute string.
 *
 * @param string        $attributes Attribute string or complete opening tag.
 * @param array<string> $names Attribute names.
 * @return string
 */
function bemke_child_remove_html_attributes( $attributes, $names ) {
	foreach ( $names as $name ) {
		$attribute_pattern = '/\s' . preg_quote( $name, '/' ) . '(?![A-Za-z0-9_:-])(?:\s*=\s*(?:["\'][^"\']*["\']|[^\s>]+))?/i';
		$updated_attributes = preg_replace( $attribute_pattern, '', $attributes );

		if ( null !== $updated_attributes ) {
			$attributes = $updated_attributes;
		}
	}

	return $attributes;
}
