<?php
/**
 * Automatic image optimization for media uploaded to WordPress.
 *
 * Generated JPEG and WebP files use a shared quality setting. JPEG uploads keep
 * their original format, while their generated responsive variants are saved as
 * WebP when the active WordPress image editor supports it.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

const BEMKE_CHILD_IMAGE_QUALITY           = 78;
const BEMKE_CHILD_IMAGE_MAX_DIMENSION     = 2560;
const BEMKE_CHILD_IMAGE_OPTIMIZER_VERSION = 'q78-v1';

add_filter( 'wp_editor_set_quality', 'bemke_child_set_image_quality', 10, 3 );
add_filter( 'jpeg_quality', 'bemke_child_set_legacy_jpeg_quality', 10, 2 );
add_filter( 'image_editor_output_format', 'bemke_child_set_image_output_format', 10, 3 );
add_filter( 'big_image_size_threshold', 'bemke_child_set_big_image_threshold', 10, 4 );
add_filter( 'wp_generate_attachment_metadata', 'bemke_child_optimize_attachment_source', 20, 3 );
add_filter( 'wp_get_attachment_image_attributes', 'bemke_child_set_responsive_image_sizes', 90, 3 );

/**
 * Set the compression quality for JPEG and WebP files generated by WordPress.
 */
function bemke_child_set_image_quality( $quality, $mime_type, $size = array() ) {
	unset( $size );

	if ( in_array( $mime_type, array( 'image/jpeg', 'image/webp' ), true ) ) {
		return BEMKE_CHILD_IMAGE_QUALITY;
	}

	return $quality;
}

/**
 * Cover older image-editor code paths which still use jpeg_quality.
 */
function bemke_child_set_legacy_jpeg_quality( $quality, $context = '' ) {
	unset( $quality, $context );

	return BEMKE_CHILD_IMAGE_QUALITY;
}

/**
 * Generate responsive variants of JPEG uploads as WebP when possible.
 *
 * The uploaded source JPEG stays a JPEG. Only the files generated by WordPress
 * for srcset are converted, so Media Library compatibility is preserved.
 */
function bemke_child_set_image_output_format( $formats, $filename = '', $mime_type = '' ) {
	unset( $filename, $mime_type );

	if (
		function_exists( 'wp_image_editor_supports' ) &&
		wp_image_editor_supports( array( 'mime_type' => 'image/webp' ) )
	) {
		$formats['image/jpeg'] = 'image/webp';
	}

	return $formats;
}

/**
 * Prevent accidental multi-thousand-pixel uploads from becoming the served full size.
 */
function bemke_child_set_big_image_threshold( $threshold, $imagesize, $file, $attachment_id ) {
	unset( $threshold, $imagesize, $file, $attachment_id );

	return BEMKE_CHILD_IMAGE_MAX_DIMENSION;
}

/**
 * Compress the primary JPEG/WebP attachment once, after WordPress has handled
 * orientation, large-image scaling and responsive sub-sizes.
 */
function bemke_child_optimize_attachment_source( $metadata, $attachment_id, $context ) {
	if ( 'create' !== $context || ! wp_attachment_is_image( $attachment_id ) ) {
		return $metadata;
	}

	if (
		BEMKE_CHILD_IMAGE_OPTIMIZER_VERSION ===
		get_post_meta( $attachment_id, '_bemke_child_image_optimizer', true )
	) {
		return $metadata;
	}

	$file = get_attached_file( $attachment_id );

	if ( ! $file || ! is_readable( $file ) || ! is_writable( $file ) ) {
		return $metadata;
	}

	$file_type = wp_check_filetype( $file );
	$mime_type = ! empty( $file_type['type'] )
		? $file_type['type']
		: get_post_mime_type( $attachment_id );

	if ( ! in_array( $mime_type, array( 'image/jpeg', 'image/webp' ), true ) ) {
		return $metadata;
	}

	$editor = wp_get_image_editor( $file );

	if ( is_wp_error( $editor ) ) {
		bemke_child_log_image_optimizer_error( $attachment_id, $editor );
		return $metadata;
	}

	if ( 'image/jpeg' === $mime_type ) {
		$rotation_result = $editor->maybe_exif_rotate();

		if ( is_wp_error( $rotation_result ) ) {
			bemke_child_log_image_optimizer_error( $attachment_id, $rotation_result );
			return $metadata;
		}
	}

	$quality_result = $editor->set_quality( BEMKE_CHILD_IMAGE_QUALITY );

	if ( is_wp_error( $quality_result ) ) {
		bemke_child_log_image_optimizer_error( $attachment_id, $quality_result );
		return $metadata;
	}

	$path_info      = pathinfo( $file );
	$temp_extension = isset( $path_info['extension'] ) ? $path_info['extension'] : '';

	if ( '' === $temp_extension ) {
		return $metadata;
	}

	$temp_filename = wp_unique_filename(
		dirname( $file ),
		$path_info['filename'] . '-bemke-optimized.' . $temp_extension
	);
	$temp_path = trailingslashit( dirname( $file ) ) . $temp_filename;

	// Preserve the uploaded source format; the WebP mapping is only for sub-sizes.
	remove_filter( 'image_editor_output_format', 'bemke_child_set_image_output_format', 10 );
	$saved = $editor->save( $temp_path, $mime_type );
	add_filter( 'image_editor_output_format', 'bemke_child_set_image_output_format', 10, 3 );

	if (
		is_wp_error( $saved ) ||
		empty( $saved['path'] ) ||
		! is_readable( $saved['path'] ) ||
		wp_normalize_path( $saved['path'] ) === wp_normalize_path( $file ) ||
		( ! empty( $saved['mime-type'] ) && $mime_type !== $saved['mime-type'] )
	) {
		if ( is_wp_error( $saved ) ) {
			bemke_child_log_image_optimizer_error( $attachment_id, $saved );
		}

		if (
			! is_wp_error( $saved ) &&
			! empty( $saved['path'] ) &&
			wp_normalize_path( $saved['path'] ) !== wp_normalize_path( $file ) &&
			file_exists( $saved['path'] )
		) {
			wp_delete_file( $saved['path'] );
		} elseif ( file_exists( $temp_path ) ) {
			wp_delete_file( $temp_path );
		}

		return $metadata;
	}

	$original_size  = wp_filesize( $file );
	$optimized_size = wp_filesize( $saved['path'] );

	$optimization_finished = false;

	if (
		false !== $original_size &&
		false !== $optimized_size &&
		$optimized_size > 0 &&
		$optimized_size >= $original_size
	) {
		$optimization_finished = true;
	} elseif (
		false !== $optimized_size &&
		$optimized_size > 0 &&
		copy( $saved['path'], $file )
	) {
		clearstatcache( true, $file );
		$metadata['filesize']  = wp_filesize( $file );
		$optimization_finished = true;
	}

	wp_delete_file( $saved['path'] );

	if ( $optimization_finished ) {
		update_post_meta(
			$attachment_id,
			'_bemke_child_image_optimizer',
			BEMKE_CHILD_IMAGE_OPTIMIZER_VERSION
		);
	}

	return $metadata;
}

/**
 * Tell browsers how wide a normal home-page slider card can actually render.
 */
function bemke_child_set_responsive_image_sizes( $attr, $attachment, $size ) {
	unset( $attachment, $size );

	if ( empty( $attr['class'] ) ) {
		return $attr;
	}

	$classes = preg_split( '/\s+/', trim( $attr['class'] ) );

	if ( ! in_array( 'slider-img', $classes, true ) ) {
		return $attr;
	}

	$attr['sizes'] = '(max-width: 767px) 72vw, (max-width: 1023px) 48vw, (max-width: 1199px) 33vw, (max-width: 1440px) 40vw, (max-width: 1660px) 48vw, 1024px';

	return $attr;
}

/**
 * Keep upload failures non-blocking while exposing details in debug.log.
 */
function bemke_child_log_image_optimizer_error( $attachment_id, $error ) {
	if ( ! defined( 'WP_DEBUG' ) || ! WP_DEBUG || ! is_wp_error( $error ) ) {
		return;
	}

	error_log(
		sprintf(
			'Bemke image optimizer failed for attachment %d: %s',
			(int) $attachment_id,
			$error->get_error_message()
		)
	);
}
